Support MediaSite composite videos
UbiCastTeam/mediasite-migration-scripts pull request #9
Opened 2021-03-30 15:25 UTC by fthiery

2021-04-12 16:01 UTC, sschoorens requested changes

2021-04-12 17:50 UTC, fthiery commented on bin/merge.py
> +        self.output_file = output_file = folder / 'composite.mp4'
C'est la manière dont pathlib fonctionne, cf https://docs.python.org/fr/3/library/pathlib.html#basic-use

2021-04-12 17:52 UTC, fthiery commented on bin/merge.py
> +                percent = int(struct.get_value('percent'))
oui

2021-04-12 17:53 UTC, fthiery commented on bin/merge.py
> +                percent = int(struct.get_value('percent'))
https://github.com/GStreamer/gst-plugins-good/blob/master/gst/debugutils/progressreport.c#L216 (c'est un double)

2021-05-06 13:48 UTC, sschoorens requested changes

2021-05-06 13:48 UTC, sschoorens commented on bin/play.py
> +            pres_id = presentation["id"]
double quote

2021-05-06 13:48 UTC, sschoorens commented on mediasite_migration_scripts/mediatransfer.py
> +        logger.debug(f"Uploading local file (composite video) : {file_path}")
double quote

2021-05-06 13:48 UTC, sschoorens commented on mediasite_migration_scripts/mediatransfer.py
> +        for f in video_files:
il faudrait probablement nommer `f` qui était `v` en quelque chose de lisible genre `video_data`

2021-05-06 13:48 UTC, sschoorens commented on mediasite_migration_scripts/video_compositor.py
> +            video_path = media_folder / f"{video_url.split('/')[-1].split('?')[0]}"
tu cherche le nom de la video via l'url ?

2021-05-06 13:48 UTC, sschoorens commented on mediasite_migration_scripts/video_compositor.py
> +            video_path = media_folder / f"{video_url.split('/')[-1].split('?')[0]}"
en tous cas le `f''` est probablement inutile

2021-05-06 13:48 UTC, sschoorens commented on mediasite_migration_scripts/video_compositor.py
> +        with self.dl_session.get(video_url, stream=True) as r:
nommer `r` de manière compréhensible

2021-05-06 13:48 UTC, sschoorens commented on tests/e2e/e2e_composition.py
> +    def setUp(self):
il n'y a pas de test ici donc ca ne se lance pas

2021-05-07 07:19 UTC, Nestuna commented on tests/e2e/e2e_composition.py
> +    def setUp(self):
Pas compris ?

2021-05-07 09:52 UTC, merged